---
- name: Install php-fpm
  hosts: all
  become: true
  tasks:

  - name: set timezone msk
    timezone:
      name: Europe/Moscow

  - name: Update all packages
    dnf:
      name: "*"
      state: latest
      update_cache: yes

  - name: install remi repo
    dnf:
      name: "https://rpms.remirepo.net/enterprise/remi-release-8.rpm"
      state: present
      disable_gpg_check: yes

  - name: enable remi
    command: dnf module enable php:remi-7.4 -y

  - name: install php
    dnf:
      name: "{{ item }}"
      state: present
    loop:
      - php
      - php-cli
      - php-common
      - php-fpm
      - php-gd
      - php-intl
      - php-mbstring
      - php-pdo
      - php-pgsql
#      - php-mysql
#      - php-soap
      - php-opcache
      - php-json
      - php-xml
      - php-xmlrpc
#      - php-imagick
#      - ImageMagick
#      - php-memcached
#      - php-redis
#      - redis
#      - memcached
      - php-devel
      - php-pear

  - name: add php-fpm conf
    template:
      src: php.conf
      dest: "/etc/php-fpm.d/php-test.conf"

  - name: Enable php-fpm
    systemd:
      name: php-fpm
      state: restarted
      enabled: yes