---
- hosts: all

  roles:
    - general-el8
    - become: yes
    # - selinux

- hosts: nginx_hosts

  roles:
   - nginx

# - hosts: backend_hosts

#   roles:
#    - php-fpm_el8

# - hosts: db_hosts

#   roles:
#    - postgresql-ol8
